//! SPDX-License-Identifier: Apache-2.0
//! Copyright 2026 ANLACO
//!
//! gRPC↔function bridge (ADR-0015): serves an Anvil step component `.wasm`
//! (the `anvil:step` interface, a `run` function) as a gRPC executor on
//! loopback. The engine talks to it over the same `paso.proto` as always; the
//! user's `.wasm` knows nothing of gRPC or protobuf — it only exports
//! `run(name, attempt, inputs) -> step-result`.
//!
//! Usage:
//!   anvil-exec-wasm --wasm <path.wasm> [--port <port>] [--bind <ip>]
//!
//! - `--wasm`: path to the component (required).
//! - `--port`: port to listen on. `anvil-host` always passes a concrete one
//!   (it reserves `127.0.0.1:0` before spawning, as it already did for the
//!   gRPC `.wasm` guests). Defaults to 0 (ephemeral; only useful by hand,
//!   since there is no way to learn the assigned port).
//! - `--bind`: IP to bind to; defaults to 127.0.0.1 (loopback-only).
//!   `--bind 0.0.0.0` enables the remote case (Raspberry Pi).
//!
//! The bridge is NATIVE Anvil code: that is why it can use tonic (unlike the
//! WASM guests, which use wasi-grpc). anvil-host spawns it from the file that
//! ships next to it (ADR-0023): it lives beside the `anvil` binary, and the
//! same file can be copied and launched by hand.

use std::net::{IpAddr, SocketAddr};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::thread;

use tonic::{transport::Server, Request, Response, Status};
use wasmtime::component::{bindgen, Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxView, WasiView};

/// `paso.proto` compiled by `build.rs` with tonic (no `package` in the
/// `.proto`, so tonic generates the root module `_`).
///
/// `clippy::result_large_err` at module level: the `StepExecutor` trait tonic
/// generates returns `Result<_, tonic::Status>` (176 bytes) from every method,
/// and since clippy 1.98 the lint also reaches generated code. Boxing the
/// error is not in our hands —tonic-build writes it— and the reasoning is the
/// same as in `LoadedComponent::call`: it is tonic's canonical error type, and
/// this is called once per step, not in a hot loop.
#[allow(clippy::result_large_err)]
pub mod pb {
    tonic::include_proto!("_");
}

use exports::anvil::step::step::Named;
use pb::step_executor_server::{StepExecutor, StepExecutorServer};
use pb::{Catalog, CatalogRequest, StepRequest, StepResult};

/// The contract version this bridge speaks (ADR-0020 §4).
///
/// **It is copied by hand, and that is exactly what the ADR warns is
/// dangerous.** It cannot be imported from `modelo` because this crate
/// deliberately does not link it: `modelo` uses prost 0.14 and the `pb` here is
/// generated by tonic 0.12 with prost 0.13 (see `Cargo.toml`).
///
/// What keeps them from drifting apart is the test
/// `the_bridge_contract_is_the_one_in_modelo`, which does link `modelo` (as a
/// dev-dependency, without touching the binary) and compares the two numbers.
/// If someone raises the contract in `modelo` and forgets this one, that test
/// goes red — which is the difference between a compile error and **an echo
/// that lies**.
const CONTRACT: i32 = 4;

// Bindings for the `anvil:step` WIT (this crate's `wit/` is the source of
// truth for the contract; the component's author uses the same file).
bindgen!({
    path: "wit",
    world: "anvil-step",
});

/// The component's state: WASI context (empty — the component is a pure
/// function, with no files and no network) plus wasmtime's resource table.
struct State {
    wasi: WasiCtx,
    table: ResourceTable,
}

impl WasiView for State {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// The instantiated component, ready for `run` to be called. It is loaded
/// **once** at start-up (preload, like TestStand) and reused for every call:
/// 1 Store, N calls.
struct LoadedComponent {
    store: Store<State>,
    step: AnvilStep,
}

/// Tells apart, by looking at the 8 header bytes, the two failures wasmtime
/// reports with the **same** text ("failed to parse WebAssembly module"): a
/// file that is not WASM at all, and a *core* module compiled as such instead
/// of as a component. The second is stumble #1 for whoever writes their first
/// step, and wasmtime's message makes them blame the toolchain (DIAG-5).
///
/// The header is `\0asm` + version: core modules carry `01 00 00 00` and
/// components `0d 00 01 00` (layer 1). Looking at the bytes, rather than at the
/// error text, keeps the diagnosis safe from wasmtime rewording it.
fn diagnose_not_a_component(bytes: &[u8]) -> Option<String> {
    if bytes.len() < 8 || &bytes[0..4] != b"\0asm" {
        return Some(
            "not a WebAssembly file: it does not start with the '\\0asm' header".to_string(),
        );
    }
    if bytes[4..8] == [0x01, 0x00, 0x00, 0x00] {
        return Some(
            "this is a WebAssembly core module, not a component: build it with \
             'cargo build --target wasm32-wasip2' and check that the crate calls \
             'anvil_step::export!()' (see docs/guia-inicio-rapido.md)"
                .to_string(),
        );
    }
    None
}

impl LoadedComponent {
    fn load(engine: &Engine, bytes: &[u8]) -> Result<Self, String> {
        // Before instantiating anything: if the `.wasm` is not a component,
        // say so with the real reason instead of wasmtime's generic one.
        if let Some(diag) = diagnose_not_a_component(bytes) {
            return Err(diag);
        }
        let mut linker = Linker::new(engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| format!("WASI linker: {e}"))?;
        // No preopens and no network: a real sandbox. The component only does
        // its job; it does not touch the host.
        let state = State {
            wasi: WasiCtx::builder().build(),
            table: ResourceTable::new(),
        };
        let mut store = Store::new(engine, state);
        let component =
            Component::from_binary(engine, bytes).map_err(|e| format!("invalid component: {e}"))?;
        let step = AnvilStep::instantiate(&mut store, &component, &linker)
            .map_err(|e| format!("could not instantiate: {e}"))?;
        Ok(LoadedComponent { store, step })
    }

    /// Calls the component's `run` and translates the result into the
    /// contract's protobuf. A guest failure (panic, trap) is reported as
    /// `Status::internal`: the engine sees it as a step error, and does not cut
    /// the sequence over the network.
    // `clippy::result_large_err`: the `Err` is `tonic::Status` (176 bytes),
    // tonic's canonical error type. Boxing it just for this method would force
    // unwrapping it at every point where tonic expects it, in exchange for
    // nothing: this is called once per step, not in a hot loop.
    #[allow(clippy::result_large_err)]
    fn call(&mut self, name: &str, attempt: i32, inputs: &[Named]) -> Result<StepResult, Status> {
        let r = self
            .step
            .anvil_step_step()
            .call_run(&mut self.store, name, attempt, inputs)
            .map_err(|e| Status::internal(format!("step '{name}' failed: {e}")))?;
        Ok(StepResult {
            name: name.to_string(),
            status: r.status,
            message: r.message,
            measured_value: r.measured_value.map(|v| v.to_string()).unwrap_or_default(),
            limit_min: String::new(),
            limit_max: String::new(),
            outputs: r.outputs.iter().map(named_to_proto).collect(),
            // **The bridge answers the echo on the component's behalf**
            // (ADR-0020 §4d). A component knows nothing of gRPC, protobuf or
            // contract versions (ADR-0015); the bridge is the only translator,
            // and therefore the only one that knows which contract number goes
            // with which WIT version. If it got this far, the `.wasm` matched
            // `anvil:step@0.4.0` —wasmtime fails to instantiate otherwise— so
            // it speaks this binary's contract.
            contract: CONTRACT,
        })
    }

    /// Asks the component for its catalog and translates it into the
    /// contract's protobuf.
    ///
    /// Called once, at start-up (ADR-0021 §3), and its cost is that of one WASM
    /// call: the component returns a list built at compile time by the SDK.
    #[allow(clippy::result_large_err)]
    fn describe(&mut self) -> Result<Vec<pb::StepSpec>, Status> {
        let specs = self
            .step
            .anvil_step_step()
            .call_describe(&mut self.store)
            .map_err(|e| {
                Status::internal(format!("the component could not describe itself: {e}"))
            })?;
        Ok(specs.iter().map(spec_to_proto).collect())
    }
}

/// The `StepExecutor` gRPC service (the engine's contract). Every `Invoke`
/// delegates to the loaded component.
///
/// The `Mutex` is the standard (blocking) one: wasmtime's `run` call is
/// synchronous and the engine is sequential (one request at a time per
/// client), so there is no contention. If parallelism ever arrives,
/// `spawn_blocking` is what keeps the async runtime from stalling.
struct ExecutorService {
    component: Arc<Mutex<LoadedComponent>>,
}

#[tonic::async_trait]
impl StepExecutor for ExecutorService {
    // `clippy::result_large_err`: the `Err` is `tonic::Status`, tonic's
    // canonical error type — see the note on `LoadedComponent::call`.
    #[allow(clippy::result_large_err)]
    async fn invoke(&self, request: Request<StepRequest>) -> Result<Response<StepResult>, Status> {
        let req = request.into_inner();
        // A parameter whose `oneof` arrived with no branch does not say what
        // type it is. It cannot be passed to the component, and it cannot be
        // silently dropped: dropping it would mean the step measured without it
        // and nobody found out (ADR-0019, Rule 2).
        let inputs = req
            .inputs
            .iter()
            .map(proto_to_named)
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| match e {
                NotTranslatable::Untyped(n) => Status::invalid_argument(format!(
                    "parameter '{n}' arrived with no type (none of the number/text/boolean branches)"
                )),
                NotTranslatable::Reference(n) => Status::invalid_argument(format!(
                    "parameter '{n}' is an object reference, and a WASM component cannot hold \
                     one: the 'anvil:step' interface is a function with no state between calls, \
                     so it has nowhere to keep the object. Serve that step from a 'grpc' \
                     executor of its own process (ADR-0022 §8)"
                )),
            })?;
        // `block_in_place`: the wasmtime call is **blocking**, and the
        // synchronous WASI bindings do a `block_on` over the tokio runtime from
        // the inside to service the component's stdout/stderr. Called directly
        // from this async method, a step's first `println!` —or the message a
        // `panic!` prints— dies with "Cannot start a runtime from within a
        // runtime", takes the bridge's worker down with it and cuts the
        // sequence with the unit on the bench. Moving the call off the thread
        // that drives the runtime is what keeps a debug print a debug print
        // (RF-12).
        let response = tokio::task::block_in_place(|| {
            let mut comp = self
                .component
                .lock()
                .map_err(|_| Status::internal("component in use"))?;
            comp.call(&req.name, req.attempt, &inputs)
        })?;
        Ok(Response::new(response))
    }

    /// The component's catalog, asked through the WIT's second door
    /// (`anvil:step@0.4.0`) and translated (ADR-0021 §1, ADR-0024).
    ///
    /// Until 0.4.0 this answered `describes = false` and there was nothing else
    /// it could do: the interface exported a single `run(name, attempt,
    /// inputs)`, the component dispatched by name inside itself, and from out
    /// here there was no list of names to publish and no signature to read. The
    /// WIT embedded in the `.wasm` did not help either — it said *"there is a
    /// `run` that takes a name and a list"*, which is true and useless. That
    /// was the bill for dispatching by name (ADR-0003); `describe` is the bill
    /// being paid.
    ///
    /// **An empty list is read as `describes = false`.** In gRPC the boolean
    /// tells apart "I serve nothing" from "do not check me" because an
    /// executor can legitimately serve zero steps; a component that serves
    /// zero steps has nothing to do, so the safe reading is the only useful
    /// one (ADR-0021 §4).
    ///
    /// A component that traps while describing itself is **not** a run-stopping
    /// error here: it comes back as `describes = false`, its steps come out as
    /// unchecked, and the sequence goes on — the same treatment as an executor
    /// that does not answer at all (`crates/motor/src/catalogo.rs`).
    #[allow(clippy::result_large_err)]
    async fn describe(&self, _r: Request<CatalogRequest>) -> Result<Response<Catalog>, Status> {
        // `block_in_place` for the same reason as in `invoke`, above.
        let steps = tokio::task::block_in_place(|| {
            self.component
                .lock()
                .map_err(|_| Status::internal("component in use"))?
                .describe()
        })?;
        Ok(Response::new(Catalog {
            describes: !steps.is_empty(),
            steps,
            contract: CONTRACT,
            // Empty on purpose: with no objects there is no life to declare
            // (ADR-0022 §6). A component cannot hold one — the bridge rejects
            // a reference before it gets here.
            lifetime: String::new(),
        }))
    }
}

fn parse_args() -> Result<(PathBuf, u16, IpAddr), String> {
    let mut wasm: Option<PathBuf> = None;
    let mut port: u16 = 0;
    let mut bind: IpAddr = "127.0.0.1".parse().unwrap();
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--wasm" => {
                i += 1;
                wasm = Some(PathBuf::from(args.get(i).ok_or("--wasm with no value")?));
            }
            "--port" => {
                i += 1;
                port = args
                    .get(i)
                    .ok_or("--port with no value")?
                    .parse()
                    .map_err(|_| "--port is not a number")?;
            }
            "--bind" => {
                i += 1;
                bind = args
                    .get(i)
                    .ok_or("--bind with no value")?
                    .parse()
                    .map_err(|_| "--bind is not a valid IP")?;
            }
            other => return Err(format!("unknown flag: '{other}'")),
        }
        i += 1;
    }
    Ok((wasm.ok_or("missing --wasm <path.wasm>")?, port, bind))
}

fn main() {
    let (wasm_path, port, bind) = match parse_args() {
        Ok(x) => x,
        Err(e) => {
            eprintln!(
                "usage: anvil-exec-wasm --wasm <path.wasm> [--port <port>] [--bind <ip>]\n{e}"
            );
            std::process::exit(2);
        }
    };

    let bytes = match std::fs::read(&wasm_path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("could not read '{}': {e}", wasm_path.display());
            std::process::exit(1);
        }
    };

    let engine = Engine::default();

    // Preload: instantiate the component at start-up (1 Store, N calls).
    let component = match LoadedComponent::load(&engine, &bytes) {
        Ok(c) => c,
        Err(e) => {
            eprintln!(
                "could not load the component '{}': {e}",
                wasm_path.display()
            );
            std::process::exit(1);
        }
    };
    let component = Arc::new(Mutex::new(component));

    let addr = SocketAddr::new(bind, port);
    let service = ExecutorService { component };

    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("could not create the runtime: {e}");
            std::process::exit(1);
        }
    };

    let server = Server::builder()
        .add_service(StepExecutorServer::new(service))
        .serve(addr);

    eprintln!("anvil-exec-wasm: loaded '{}'", wasm_path.display());
    eprintln!("anvil-exec-wasm: listening on {addr}");

    // Clean exit: the host spawns the bridge with stdin piped; when the host
    // dies (or drops the `Child`), the pipe closes → EOF → the bridge exits.
    // Without this, a dead host would leave the bridge orphaned.
    let current_stdin = std::io::stdin();
    let _ = thread::spawn(move || {
        let mut buf = [0u8; 1];
        while let Ok(n) = std::io::Read::read(&mut current_stdin.lock(), &mut buf) {
            if n == 0 {
                std::process::exit(0);
            }
        }
    });

    // The server does not finish on its own (a loop serving requests). The
    // host kills the process when the sequence ends; by hand, Ctrl-C.
    let _ = rt.block_on(server);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A core module's header: `\0asm` + version 1.
    const CORE_MODULE_HEADER: [u8; 8] = [0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00];
    /// A component's header: `\0asm` + version 13, layer 1.
    const COMPONENT_HEADER: [u8; 8] = [0x00, 0x61, 0x73, 0x6d, 0x0d, 0x00, 0x01, 0x00];

    #[test]
    fn a_core_module_is_diagnosed_as_such() {
        let diag = diagnose_not_a_component(&CORE_MODULE_HEADER).expect("must diagnose");
        assert!(diag.contains("core module"), "{diag}");
        // The message has to name the RIGHT tool: since the SDK (ADR-0024) a
        // step is built with the plain toolchain, and sending someone to
        // install `cargo component` would send whoever is already lost down
        // the wrong road.
        assert!(
            diag.contains("cargo build --target wasm32-wasip2"),
            "{diag}"
        );
    }

    #[test]
    fn a_component_does_not_trigger_the_diagnosis() {
        assert_eq!(diagnose_not_a_component(&COMPONENT_HEADER), None);
    }

    /// A component broken **beyond** the header is not this diagnosis's
    /// business: there wasmtime's message is the good one.
    #[test]
    fn a_component_with_a_junk_body_is_left_to_wasmtime() {
        let mut bytes = COMPONENT_HEADER.to_vec();
        bytes.extend_from_slice(&[0xff; 16]);
        assert_eq!(diagnose_not_a_component(&bytes), None);
    }

    #[test]
    fn a_file_that_is_not_wasm_is_diagnosed() {
        let diag = diagnose_not_a_component(b"name: i am not a wasm\n").expect("must diagnose");
        assert!(diag.contains("not a WebAssembly file"), "{diag}");
    }

    #[test]
    fn a_file_shorter_than_the_header_is_diagnosed() {
        let diag = diagnose_not_a_component(&COMPONENT_HEADER[..4]).expect("must diagnose");
        assert!(diag.contains("not a WebAssembly file"), "{diag}");
    }
}

/// A WIT `Named` into the protobuf `Value` (the component's output).
fn named_to_proto(n: &Named) -> pb::Value {
    use exports::anvil::step::step::Value as ValueWit;
    let data = match &n.value {
        ValueWit::Number(x) => pb::value::Value::Number(*x),
        ValueWit::Text(s) => pb::value::Value::Text(s.clone()),
        ValueWit::Boolean(b) => pb::value::Value::Boolean(*b),
    };
    pb::Value {
        name: n.name.clone(),
        value: Some(data),
    }
}

/// The WIT's `value-type` into the protobuf `ValueType`.
///
/// The WIT has no `reference` (ADR-0022 §8), which is why the `match` is total
/// with no catch-all arm: if the WIT ever gains a type, this stops compiling,
/// which is exactly what is wanted.
fn type_to_proto(t: exports::anvil::step::step::ValueType) -> i32 {
    use exports::anvil::step::step::ValueType as TypeWit;
    let t = match t {
        TypeWit::Unspecified => pb::ValueType::Unspecified,
        TypeWit::Number => pb::ValueType::Number,
        TypeWit::Text => pb::ValueType::Text,
        TypeWit::Boolean => pb::ValueType::Boolean,
    };
    t as i32
}

/// A bare WIT `value` into the protobuf `Value`, with no name.
///
/// Only a parameter's `default` uses it, and that travels unnamed because the
/// name is already on the `ParameterSpec` holding it.
fn value_to_proto(v: &exports::anvil::step::step::Value) -> pb::Value {
    use exports::anvil::step::step::Value as ValueWit;
    let data = match v {
        ValueWit::Number(x) => pb::value::Value::Number(*x),
        ValueWit::Text(s) => pb::value::Value::Text(s.clone()),
        ValueWit::Boolean(b) => pb::value::Value::Boolean(*b),
    };
    pb::Value {
        name: String::new(),
        value: Some(data),
    }
}

/// A WIT `step-spec` into the protobuf `StepSpec`: the catalog, translated.
fn spec_to_proto(s: &exports::anvil::step::step::StepSpec) -> pb::StepSpec {
    pb::StepSpec {
        name: s.name.clone(),
        inputs: s
            .inputs
            .iter()
            .map(|p| pb::ParameterSpec {
                name: p.name.clone(),
                r#type: type_to_proto(p.type_),
                required: p.required,
                default: p.default.as_ref().map(value_to_proto),
                doc: p.doc.clone(),
            })
            .collect(),
        outputs: s
            .outputs
            .iter()
            .map(|o| pb::OutputSpec {
                name: o.name.clone(),
                r#type: type_to_proto(o.type_),
                doc: o.doc.clone(),
            })
            .collect(),
        doc: s.doc.clone(),
    }
}

/// Why a protobuf `Value` cannot be passed to the component.
#[derive(Debug, PartialEq)]
enum NotTranslatable {
    /// The `oneof` arrived empty: it does not say what type it is.
    Untyped(String),
    /// It is an object reference (ADR-0022).
    Reference(String),
}

/// A protobuf `Value` into the WIT's `Named` (the input parameter).
///
/// `Err` when there is no way to build the WIT `variant`, and the WIT has no
/// "unknown" arm on purpose: that is what makes it impossible to hand the
/// component a parameter nobody knows how to read. Two reasons:
///
/// - **The `oneof` arrived empty**: it does not say what type it is.
/// - **It is a reference** (contract 4, ADR-0022). This bridge's WIT is
///   `run(name, attempt, inputs) -> step-result`: a function, with no resources
///   and no state between calls (ADR-0020 §4d), so the user's component **has
///   nowhere to keep the object**. Handing it a reference would be handing it
///   an identifier it cannot resolve.
///
///   The failure is explicit and never a silence, which is exactly what
///   ADR-0022 §8 demands while the WIT stays untouched: giving the WASM state
///   is a decision with its own ADR, and until then this is said out loud.
fn proto_to_named(v: &pb::Value) -> Result<Named, NotTranslatable> {
    use exports::anvil::step::step::Value as ValueWit;
    let value = match v
        .value
        .as_ref()
        .ok_or_else(|| NotTranslatable::Untyped(v.name.clone()))?
    {
        pb::value::Value::Number(x) => ValueWit::Number(*x),
        pb::value::Value::Text(s) => ValueWit::Text(s.clone()),
        pb::value::Value::Boolean(b) => ValueWit::Boolean(*b),
        pb::value::Value::Reference(_) => return Err(NotTranslatable::Reference(v.name.clone())),
    };
    Ok(Named {
        name: v.name.clone(),
        value,
    })
}

#[cfg(test)]
mod contract_tests {
    use super::*;

    /// The net holding up the hand-copied `const CONTRACT`. See its comment:
    /// the bridge cannot link `modelo` into the binary, so the only way to keep
    /// the two copies together is to compare them in a test.
    #[test]
    fn the_bridge_contract_is_the_one_in_modelo() {
        assert_eq!(
            CONTRACT,
            modelo::proto::CONTRACT,
            "the bridge answers the echo on behalf of WASM components: if its \
             number falls behind, it claims to understand a contract it does not"
        );
    }

    #[test]
    fn an_untyped_parameter_does_not_reach_the_component() {
        // ADR-0019 Rule 2 at the bridge's border. If this started returning
        // `Ok`, a step would measure without a parameter it was sent.
        let v = pb::Value {
            name: "channel".into(),
            value: None,
        };
        assert_eq!(
            proto_to_named(&v).unwrap_err(),
            NotTranslatable::Untyped("channel".into())
        );
    }

    /// ADR-0022 §8: a reference reaching a WASM component is an **explicit**
    /// error, never a silence.
    ///
    /// This bridge's WIT is `run(name, attempt, inputs)`: a function, with no
    /// resources and no state between calls, so the component has nowhere to
    /// keep the object. Giving it state is a decision with its own ADR; until
    /// then this is said out loud, in the place that knows.
    ///
    /// Seen to fail by adding an arm turning it into `ValueWit::Text` with the
    /// payload: `proto_to_named` returns `Ok` and the component receives a
    /// string it cannot resolve.
    #[test]
    fn a_reference_does_not_reach_a_wasm_component() {
        let v = pb::Value {
            name: "rack".into(),
            value: Some(pb::value::Value::Reference(pb::Reference {
                executor: "bench".into(),
                lifetime: "v1".into(),
                payload: "s1".into(),
            })),
        };
        assert_eq!(
            proto_to_named(&v).unwrap_err(),
            NotTranslatable::Reference("rack".into())
        );
    }

    #[test]
    fn the_three_types_cross_the_border_both_ways() {
        use exports::anvil::step::step::Value as ValueWit;
        for wit in [
            ValueWit::Number(4.2),
            ValueWit::Text("bench-3".into()),
            ValueWit::Boolean(true),
        ] {
            let n = Named {
                name: "p".into(),
                value: wit,
            };
            let there = named_to_proto(&n);
            let back = proto_to_named(&there).expect("a typed value always comes back");
            assert_eq!(back.name, "p");
            assert_eq!(named_to_proto(&back), there);
        }
    }
}
