//! SPDX-License-Identifier: Apache-2.0
//! Copyright 2026 ANLACO
//!
//! gRPC↔function bridge (ADR-0015): serves an Anvil step component `.wasm`
//! (the `anvil:step` interface, a `run` function) as a gRPC executor on
//! loopback. The engine talks to it over the same `paso.proto` as always; the
//! user's `.wasm` knows nothing of gRPC or protobuf — it only exports
//! `run(name, attempt, inputs) -> step-result`.
//!
//! Usage:
//!   anvil-exec-wasm [--modules <dir>... | --wasm <path.wasm>] [--port <port>]
//!                   [--bind <ip>] [--list]
//!
//! It serves **one or more modules** (ADR-0025): a department that loads a
//! folder of components, not the component itself. A module's logical name is
//! its file stem, and a step is named `<module>/<step>`, so neither the
//! extension nor any path reaches a sequence.
//!
//! **Told nothing, it serves the folder its own binary is in** (ADR-0027).
//! That is what makes a department a copyable thing — this binary with its
//! `.wasm` beside it — and it is why a sequence points `path:` at *this
//! executor* and never at a module: where the modules are is this process's
//! business, not the sequence's.
//!
//! - `--modules <dir>`: serve these directories instead (repeatable).
//! - `--wasm <file>`: serve exactly one file, and then steps keep their
//!   **bare** names. Only for running a component by hand; Anvil never uses
//!   it, so a step served through Anvil is always qualified.
//! - `--list`: print what is served — modules, hashes and signatures — and
//!   exit, without listening. The *enumerate* door for an editor.
//!
//! - `--port`: port to listen on. `anvil-host` always passes a concrete one
//!   (it reserves `127.0.0.1:0` before spawning, as it already did for the
//!   gRPC `.wasm` guests). Defaults to 0 (ephemeral; only useful by hand,
//!   since there is no way to learn the assigned port).
//! - `--bind`: IP to bind to; defaults to 127.0.0.1 (loopback-only).
//!   `--bind 0.0.0.0` enables the remote case (Raspberry Pi).
//!
//! The qualified name travels **inside `StepRequest.name`**, which is an opaque
//! string to `paso.proto`. That is why serving many modules costs no contract
//! change, no engine change and no WIT change.
//!
//! The bridge is NATIVE Anvil code: that is why it can use tonic (unlike the
//! WASM guests, which use wasi-grpc). It ships as a file next to `anvil`
//! (ADR-0023) — but that is only where it *arrives*: since ADR-0027 the
//! sequence names the binary to spawn, so this file gets copied into whatever
//! folder is going to be a department, and launched from there.

use std::collections::BTreeMap;
use std::net::{IpAddr, SocketAddr};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::thread;

use sha2::{Digest, Sha256};
use tonic::{transport::Server, Request, Response, Status};
use wasmtime::component::types::{self, Type as CompType};
use wasmtime::component::{bindgen, Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxView, WasiView};

/// `paso.proto` compiled by `build.rs` with tonic (no `package` in the
/// `.proto`, so tonic generates the root module `_`).
///
/// `clippy::result_large_err` at module level: the `StepExecutor` trait tonic
/// generates returns `Result<_, tonic::Status>` (176 bytes) from every method,
/// and since clippy 1.98 the lint also reaches generated code. Boxing the
/// error is not in our hands —tonic-build writes it— and the reasoning is the
/// same as in `LoadedComponent::call`: it is tonic's canonical error type, and
/// this is called once per step, not in a hot loop.
#[allow(clippy::result_large_err)]
pub mod pb {
    tonic::include_proto!("_");
}

use exports::anvil::step::step::Named;
use pb::step_executor_server::{StepExecutor, StepExecutorServer};
use pb::{Catalog, CatalogRequest, StepRequest, StepResult};

/// The contract version this bridge speaks (ADR-0020 §4).
///
/// **It is copied by hand, and that is exactly what the ADR warns is
/// dangerous.** It cannot be imported from `modelo` because this crate
/// deliberately does not link it: `modelo` uses prost 0.14 and the `pb` here is
/// generated by tonic 0.12 with prost 0.13 (see `Cargo.toml`).
///
/// What keeps them from drifting apart is the test
/// `the_bridge_contract_is_the_one_in_modelo`, which does link `modelo` (as a
/// dev-dependency, without touching the binary) and compares the two numbers.
/// If someone raises the contract in `modelo` and forgets this one, that test
/// goes red — which is the difference between a compile error and **an echo
/// that lies**.
const CONTRACT: i32 = 4;

// Bindings for the `anvil:step` WIT (this crate's `wit/` is the source of
// truth for the contract; the component's author uses the same file).
bindgen!({
    path: "wit",
    world: "anvil-step",
});

/// The component's state: WASI context (empty — the component is a pure
/// function, with no files and no network) plus wasmtime's resource table.
struct State {
    wasi: WasiCtx,
    table: ResourceTable,
}

impl WasiView for State {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// The instantiated component, ready for `run` to be called. It is loaded
/// **once** at start-up (preload, like TestStand) and reused for every call:
/// 1 Store, N calls.
struct LoadedComponent {
    store: Store<State>,
    step: AnvilStep,
}

/// Tells apart, by looking at the 8 header bytes, the two failures wasmtime
/// reports with the **same** text ("failed to parse WebAssembly module"): a
/// file that is not WASM at all, and a *core* module compiled as such instead
/// of as a component. The second is stumble #1 for whoever writes their first
/// step, and wasmtime's message makes them blame the toolchain (DIAG-5).
///
/// The header is `\0asm` + version: core modules carry `01 00 00 00` and
/// components `0d 00 01 00` (layer 1). Looking at the bytes, rather than at the
/// error text, keeps the diagnosis safe from wasmtime rewording it.
fn diagnose_not_a_component(bytes: &[u8]) -> Option<String> {
    if bytes.len() < 8 || &bytes[0..4] != b"\0asm" {
        return Some(
            "not a WebAssembly file: it does not start with the '\\0asm' header".to_string(),
        );
    }
    if bytes[4..8] == [0x01, 0x00, 0x00, 0x00] {
        return Some(
            "this is a WebAssembly core module, not a component: build it with \
             'cargo build --target wasm32-wasip2' and check that the crate calls \
             'anvil_step::export!()' (see docs/guia-inicio-rapido.md)"
                .to_string(),
        );
    }
    None
}

/// The `anvil:step/step` interface's export key, as wit-bindgen/wasm-tools
/// name it: `<package>/<interface>@<version>` (see `wit/anvil-step.wit`).
const STEP_INTERFACE: &str = "anvil:step/step@0.4.0";

/// The signatures `wit/anvil-step.wit` declares, spelled by hand for
/// [`diagnose_signature_mismatch`] — this binary does not parse WIT text at
/// runtime, so these are not read from the file. Keep them in step with the
/// `run`/`describe` lines there.
const EXPECTED_RUN: &str =
    "run: func(name: string, attempt: s32, inputs: list<named>) -> step-result";
const EXPECTED_DESCRIBE: &str = "describe: func() -> list<step-spec>";

/// A component-model type, spelled close to its WIT syntax — deep enough to
/// name a mismatched parameter's actual type (issue #24's `u32` instead of
/// `s32`, or a `record` wrapping the arguments). Not a full WIT printer: past
/// one level of nesting a composite type just names its shape.
fn render_type(t: &CompType) -> String {
    match t {
        CompType::Bool => "bool".to_string(),
        CompType::S8 => "s8".to_string(),
        CompType::U8 => "u8".to_string(),
        CompType::S16 => "s16".to_string(),
        CompType::U16 => "u16".to_string(),
        CompType::S32 => "s32".to_string(),
        CompType::U32 => "u32".to_string(),
        CompType::S64 => "s64".to_string(),
        CompType::U64 => "u64".to_string(),
        CompType::Float32 => "float32".to_string(),
        CompType::Float64 => "float64".to_string(),
        CompType::Char => "char".to_string(),
        CompType::String => "string".to_string(),
        CompType::List(l) => format!("list<{}>", render_type(&l.ty())),
        CompType::Option(o) => format!("option<{}>", render_type(&o.ty())),
        CompType::Record(r) => {
            let fields = r
                .fields()
                .map(|f| format!("{}: {}", f.name, render_type(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("record {{ {fields} }}")
        }
        CompType::Map(_) => "map".to_string(),
        CompType::Tuple(_) => "tuple".to_string(),
        CompType::Variant(_) => "variant".to_string(),
        CompType::Enum(_) => "enum".to_string(),
        CompType::Result(_) => "result".to_string(),
        CompType::Flags(_) => "flags".to_string(),
        CompType::Own(_) | CompType::Borrow(_) => "resource".to_string(),
        CompType::Future(_) => "future".to_string(),
        CompType::Stream(_) => "stream".to_string(),
        CompType::ErrorContext => "error-context".to_string(),
    }
}

/// Renders a component-model function type as a WIT-like `name: func(...) ->
/// ...` line, the same shape as [`EXPECTED_RUN`]/[`EXPECTED_DESCRIBE`] so the
/// two read side by side.
fn render_func(name: &str, f: &types::ComponentFunc) -> String {
    let params = f
        .params()
        .map(|(n, t)| format!("{n}: {}", render_type(&t)))
        .collect::<Vec<_>>()
        .join(", ");
    let results: Vec<String> = f.results().map(|t| render_type(&t)).collect();
    let ret = match results.len() {
        0 => String::new(),
        1 => format!(" -> {}", results[0]),
        _ => format!(" -> ({})", results.join(", ")),
    };
    format!("{name}: func({params}){ret}")
}

/// Finds a function exported by a component instance, by name.
fn find_func(
    instance: &types::ComponentInstance,
    engine: &Engine,
    name: &str,
) -> Option<types::ComponentFunc> {
    instance.exports(engine).find_map(|(n, e)| match e.ty {
        types::ComponentItem::ComponentFunc(f) if n == name => Some(f),
        _ => None,
    })
}

/// Issue #24: wasmtime's own error on a signature mismatch — "failed to
/// convert function to given type" — names neither the signature the host
/// expected nor the one the component exports, so the first thing whoever
/// writes their own component sees is a message with no pointer to what is
/// wrong (BUG-06 of the beta). This inspects the component's *type* — no WASM
/// runs, it is the same static info `wasm-tools component wit` would read —
/// to say both, so the two can be compared by eye.
///
/// Always run/described side by side, even when one of the two turns out to
/// match: a `render_func` line expands named types structurally (`list<named>`
/// comes back as `list<record { name: string, value: variant }>`), so it
/// never reads identical to [`EXPECTED_RUN`]/[`EXPECTED_DESCRIBE`]'s shorthand
/// even for a correct component. Deciding "this one actually differs" would
/// need a real WIT-aware comparison; showing both lines and letting the
/// reader's eye do that is the honest alternative to a hand-rolled one that
/// could itself be wrong.
fn diagnose_signature_mismatch(component: &Component, engine: &Engine) -> String {
    let ty = component.component_type();
    let interface = ty.exports(engine).find_map(|(name, e)| match e.ty {
        types::ComponentItem::ComponentInstance(i) if name == STEP_INTERFACE => Some(i),
        _ => None,
    });
    let Some(interface) = interface else {
        let found: Vec<&str> = ty.exports(engine).map(|(n, _)| n).collect();
        return format!(
            "the component does not export '{STEP_INTERFACE}'; it exports: {}",
            if found.is_empty() {
                "(nothing)".to_string()
            } else {
                found.join(", ")
            }
        );
    };
    [("run", EXPECTED_RUN), ("describe", EXPECTED_DESCRIBE)]
        .iter()
        .map(|(name, expected)| {
            let found = find_func(&interface, engine, name)
                .map(|f| render_func(name, &f))
                .unwrap_or_else(|| format!("{name}: (not exported)"));
            format!("expected  {expected}\nexports   {found}")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

impl LoadedComponent {
    fn load(engine: &Engine, bytes: &[u8]) -> Result<Self, String> {
        // Before instantiating anything: if the `.wasm` is not a component,
        // say so with the real reason instead of wasmtime's generic one.
        if let Some(diag) = diagnose_not_a_component(bytes) {
            return Err(diag);
        }
        let mut linker = Linker::new(engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| format!("WASI linker: {e}"))?;
        // No preopens and no network: a real sandbox. The component only does
        // its job; it does not touch the host.
        let state = State {
            wasi: WasiCtx::builder().build(),
            table: ResourceTable::new(),
        };
        let mut store = Store::new(engine, state);
        let component =
            Component::from_binary(engine, bytes).map_err(|e| format!("invalid component: {e}"))?;
        let step = AnvilStep::instantiate(&mut store, &component, &linker).map_err(|e| {
            format!(
                "could not instantiate: {e}\n{}",
                diagnose_signature_mismatch(&component, engine)
            )
        })?;
        Ok(LoadedComponent { store, step })
    }

    /// Calls the component's `run` and translates the result into the
    /// contract's protobuf. A guest failure (panic, trap) is reported as
    /// `Status::internal`: the engine sees it as a step error, and does not cut
    /// the sequence over the network.
    // `clippy::result_large_err`: the `Err` is `tonic::Status` (176 bytes),
    // tonic's canonical error type. Boxing it just for this method would force
    // unwrapping it at every point where tonic expects it, in exchange for
    // nothing: this is called once per step, not in a hot loop.
    #[allow(clippy::result_large_err)]
    fn call(&mut self, name: &str, attempt: i32, inputs: &[Named]) -> Result<StepResult, Status> {
        let r = self
            .step
            .anvil_step_step()
            .call_run(&mut self.store, name, attempt, inputs)
            .map_err(|e| Status::internal(format!("step '{name}' failed: {e}")))?;
        Ok(StepResult {
            name: name.to_string(),
            status: r.status,
            message: r.message,
            measured_value: r.measured_value.map(|v| v.to_string()).unwrap_or_default(),
            limit_min: String::new(),
            limit_max: String::new(),
            outputs: r.outputs.iter().map(named_to_proto).collect(),
            // **The bridge answers the echo on the component's behalf**
            // (ADR-0020 §4d). A component knows nothing of gRPC, protobuf or
            // contract versions (ADR-0015); the bridge is the only translator,
            // and therefore the only one that knows which contract number goes
            // with which WIT version. If it got this far, the `.wasm` matched
            // `anvil:step@0.4.0` —wasmtime fails to instantiate otherwise— so
            // it speaks this binary's contract.
            contract: CONTRACT,
        })
    }

    /// Asks the component for its catalog and translates it into the
    /// contract's protobuf.
    ///
    /// Called once, at start-up (ADR-0021 §3), and its cost is that of one WASM
    /// call: the component returns a list built at compile time by the SDK.
    #[allow(clippy::result_large_err)]
    fn describe(&mut self) -> Result<Vec<pb::StepSpec>, Status> {
        let specs = self
            .step
            .anvil_step_step()
            .call_describe(&mut self.store)
            .map_err(|e| {
                Status::internal(format!("the component could not describe itself: {e}"))
            })?;
        Ok(specs.iter().map(spec_to_proto).collect())
    }
}

/// The separator between a module's logical name and a step's, in the name
/// that travels in `StepRequest.name` (ADR-0025 §2).
///
/// The qualified name rides **inside the existing field**, which is an opaque
/// string as far as `paso.proto` is concerned. That is what lets a department
/// serve many modules without touching the contract, the engine or the WIT.
const MODULE_SEP: char = '/';

/// One module the bridge serves: a `.wasm` under its working directory.
///
/// The **logical name is the file stem** (`multimetro.wasm` → `multimetro`),
/// so neither the extension nor the path ever reaches the sequence
/// (ADR-0025 §3): rewriting a module in another language, or the department
/// reorganising its folders, must not edit anybody's YAML.
struct Module {
    path: PathBuf,
    /// SHA-256 of the artifact, computed when the set is built — that is, by
    /// reading the file, without compiling anything. Asking a department for
    /// its hashes has to stay cheap, because it is what invalidates an
    /// editor's catalog cache (ADR-0025 §5).
    hash: String,
    /// `None` until something actually needs this module. Loading is what
    /// costs (wasmtime compiles the component), so it is paid per module and
    /// on demand: `--validate` with no catalog compiles nothing, and a broken
    /// `.wasm` sitting in the folder no longer takes the whole bridge down —
    /// only whoever uses it fails.
    loaded: Option<LoadedComponent>,
}

/// What this bridge serves: one or more modules, and how a step name maps onto
/// them.
struct ModuleSet {
    engine: Engine,
    modules: BTreeMap<String, Module>,
    /// Whether step names carry a `module/` prefix.
    ///
    /// It comes from what the bridge was pointed at, and the two modes are
    /// kept apart on purpose rather than blended: `--wasm <file>` serves one
    /// module and steps keep their **bare** names, which is what every
    /// sequence written before ADR-0025 says; `--modules <dir>` serves the
    /// whole folder and steps are **qualified**. Mixing them would make
    /// `medir_voltaje` mean different things depending on what else happens to
    /// be in the directory.
    qualified: bool,
}

impl ModuleSet {
    /// The single-file mode: one module, bare step names. What `--wasm` gives.
    ///
    /// This one is loaded **eagerly**, unlike the directory mode. Laziness is
    /// there so that one broken `.wasm` in a folder does not take down the
    /// modules nobody asked about; with a single file pointed at by hand there
    /// are no others, and finding out at the first step that it is not a
    /// component —or is a core module, DIAG-5— would be finding out with the
    /// unit already on the bench.
    fn from_file(engine: Engine, path: &Path) -> Result<Self, String> {
        let mut modules = BTreeMap::new();
        let (name, mut module) = read_module(path)?;
        let bytes =
            std::fs::read(path).map_err(|e| format!("could not read '{}': {e}", path.display()))?;
        module.loaded = Some(
            LoadedComponent::load(&engine, &bytes)
                .map_err(|e| format!("could not load the component '{}': {e}", path.display()))?,
        );
        modules.insert(name, module);
        Ok(ModuleSet {
            engine,
            modules,
            qualified: false,
        })
    }

    /// The directory mode: every `*.wasm` in the given directories, qualified
    /// step names. What `--modules` gives.
    fn from_dirs(engine: Engine, dirs: &[PathBuf]) -> Result<Self, String> {
        let mut modules: BTreeMap<String, Module> = BTreeMap::new();
        for dir in dirs {
            let entries = std::fs::read_dir(dir).map_err(|e| {
                format!(
                    "could not read the module directory '{}': {e}",
                    dir.display()
                )
            })?;
            for entry in entries {
                let path = entry
                    .map_err(|e| format!("could not read an entry of '{}': {e}", dir.display()))?
                    .path();
                if path.extension().and_then(|e| e.to_str()) != Some("wasm") {
                    continue;
                }
                let (name, module) = read_module(&path)?;
                // Two files with the same logical name would make a step name
                // ambiguous, and serving the wrong one is worse than not
                // starting: it would run a different step than the one the
                // sequence asked for, and the report would not say so.
                if let Some(previous) = modules.get(&name) {
                    return Err(format!(
                        "two modules are both called '{name}': '{}' and '{}'. A module's logical \
                         name is its file stem, so rename one of the two files",
                        previous.path.display(),
                        path.display()
                    ));
                }
                modules.insert(name, module);
            }
        }
        if modules.is_empty() {
            let list = dirs
                .iter()
                .map(|d| d.display().to_string())
                .collect::<Vec<_>>()
                .join(", ");
            return Err(format!(
                "no '.wasm' module found under: {list}. An executor finds its modules \
                 next to its own binary (ADR-0027), so copy them there — or point it \
                 elsewhere with --modules <dir>"
            ));
        }
        Ok(ModuleSet {
            engine,
            modules,
            qualified: true,
        })
    }

    /// Splits a step name into (module, step).
    ///
    /// In single-file mode the whole name is the step's, and the module is the
    /// only one there is. In directory mode the prefix is required: guessing a
    /// module because there happens to be one that serves that step would make
    /// the sequence's meaning depend on the folder's contents.
    fn resolve(&self, name: &str) -> Result<(String, String), String> {
        if !self.qualified {
            let module = self
                .modules
                .keys()
                .next()
                .expect("single-file mode always has exactly one module");
            return Ok((module.clone(), name.to_string()));
        }
        let (module, step) = name.split_once(MODULE_SEP).ok_or_else(|| {
            format!(
                "step '{name}' has no module: this executor serves several modules, so a step is \
                 named '<module>{MODULE_SEP}<step>'. It serves: {}",
                self.module_names()
            )
        })?;
        if !self.modules.contains_key(module) {
            return Err(format!(
                "this executor serves no module called '{module}'. It serves: {}",
                self.module_names()
            ));
        }
        Ok((module.to_string(), step.to_string()))
    }

    fn module_names(&self) -> String {
        self.modules.keys().cloned().collect::<Vec<_>>().join(", ")
    }

    /// The module's component, loading it the first time it is needed.
    fn component(&mut self, module: &str) -> Result<&mut LoadedComponent, String> {
        // Split borrow: `engine` and `modules` are different fields, and
        // taking them apart is what lets the load happen behind `&mut self`.
        let ModuleSet {
            engine, modules, ..
        } = self;
        let m = modules
            .get_mut(module)
            .ok_or_else(|| format!("unknown module '{module}'"))?;
        if m.loaded.is_none() {
            let bytes = std::fs::read(&m.path)
                .map_err(|e| format!("could not read '{}': {e}", m.path.display()))?;
            let loaded = LoadedComponent::load(engine, &bytes).map_err(|e| {
                format!(
                    "could not load the module '{module}' ({}): {e}",
                    m.path.display()
                )
            })?;
            m.loaded = Some(loaded);
        }
        Ok(m.loaded.as_mut().expect("just loaded"))
    }

    /// The catalog of every module, with each step's name qualified.
    ///
    /// A module that cannot be loaded, or that traps while describing itself,
    /// **does not take the other modules' catalog down with it**: its steps
    /// stay out and the reason goes to stderr. Anvil then reports those steps
    /// as unchecked, which is ADR-0021 §4 — not being checked is not the same
    /// as being fine, and it is said out loud.
    // `clippy::result_large_err`: the inner `Result` is `describe`'s, whose
    // `Err` is `tonic::Status` — see the note on `LoadedComponent::call`.
    #[allow(clippy::result_large_err)]
    fn catalog(&mut self) -> Vec<pb::StepSpec> {
        let names: Vec<String> = self.modules.keys().cloned().collect();
        let qualified = self.qualified;
        let mut out = Vec::new();
        for module in names {
            let specs = match self.component(&module).map(|c| c.describe()) {
                Ok(Ok(specs)) => specs,
                Ok(Err(status)) => {
                    eprintln!(
                        "anvil-exec-wasm: module '{module}' could not describe itself ({}); its \
                         steps stay unchecked",
                        status.message()
                    );
                    continue;
                }
                Err(e) => {
                    eprintln!(
                        "anvil-exec-wasm: module '{module}' could not be loaded ({e}); its steps \
                         stay unchecked"
                    );
                    continue;
                }
            };
            out.extend(specs.into_iter().map(|mut s| {
                if qualified {
                    s.name = format!("{module}{MODULE_SEP}{}", s.name);
                }
                s
            }));
        }
        out
    }
}

/// Reads a `.wasm` off disk: its logical name and its hash, without compiling
/// it. Loading is deferred to `ModuleSet::component`.
fn read_module(path: &Path) -> Result<(String, Module), String> {
    let name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| format!("'{}' has no usable file name", path.display()))?
        .to_string();
    let bytes =
        std::fs::read(path).map_err(|e| format!("could not read '{}': {e}", path.display()))?;
    let hash = format!("{:x}", Sha256::digest(&bytes));
    Ok((
        name,
        Module {
            path: path.to_path_buf(),
            hash,
            loaded: None,
        },
    ))
}

/// The `StepExecutor` gRPC service (the engine's contract). Every `Invoke`
/// resolves its module and delegates to the component.
///
/// The `Mutex` is the standard (blocking) one: wasmtime's `run` call is
/// synchronous and the engine is sequential (one request at a time per
/// client), so there is no contention. If parallelism ever arrives,
/// `spawn_blocking` is what keeps the async runtime from stalling.
struct ExecutorService {
    modules: Arc<Mutex<ModuleSet>>,
}

#[tonic::async_trait]
impl StepExecutor for ExecutorService {
    // `clippy::result_large_err`: the `Err` is `tonic::Status`, tonic's
    // canonical error type — see the note on `LoadedComponent::call`.
    #[allow(clippy::result_large_err)]
    async fn invoke(&self, request: Request<StepRequest>) -> Result<Response<StepResult>, Status> {
        let req = request.into_inner();
        // A parameter whose `oneof` arrived with no branch does not say what
        // type it is. It cannot be passed to the component, and it cannot be
        // silently dropped: dropping it would mean the step measured without it
        // and nobody found out (ADR-0019, Rule 2).
        let inputs = req
            .inputs
            .iter()
            .map(proto_to_named)
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| match e {
                NotTranslatable::Untyped(n) => Status::invalid_argument(format!(
                    "parameter '{n}' arrived with no type (none of the number/text/boolean branches)"
                )),
                NotTranslatable::Reference(n) => Status::invalid_argument(format!(
                    "parameter '{n}' is an object reference, and a WASM component cannot hold \
                     one: the 'anvil:step' interface is a function with no state between calls, \
                     so it has nowhere to keep the object. Serve that step from a 'grpc' \
                     executor of its own process (ADR-0022 §8)"
                )),
            })?;
        // `block_in_place`: the wasmtime call is **blocking**, and the
        // synchronous WASI bindings do a `block_on` over the tokio runtime from
        // the inside to service the component's stdout/stderr. Called directly
        // from this async method, a step's first `println!` —or the message a
        // `panic!` prints— dies with "Cannot start a runtime from within a
        // runtime", takes the bridge's worker down with it and cuts the
        // sequence with the unit on the bench. Moving the call off the thread
        // that drives the runtime is what keeps a debug print a debug print
        // (RF-12).
        let response = tokio::task::block_in_place(|| {
            let mut set = self
                .modules
                .lock()
                .map_err(|_| Status::internal("executor in use"))?;
            // Which module, and what the step is called inside it. A name that
            // does not resolve is `invalid_argument` and names what is served:
            // the sequence asked for something this department does not have,
            // and that is information about the bench, never about the unit
            // (ADR-0019, Rule 2).
            let (module, step) = set.resolve(&req.name).map_err(Status::invalid_argument)?;
            let mut result = set.component(&module).map_err(Status::internal)?.call(
                &step,
                req.attempt,
                &inputs,
            )?;
            // The engine routed on the qualified name and expects it back:
            // `StepResult.name` is what the report is written from.
            result.name = req.name.clone();
            Ok::<_, Status>(result)
        })?;
        Ok(Response::new(response))
    }

    /// The component's catalog, asked through the WIT's second door
    /// (`anvil:step@0.4.0`) and translated (ADR-0021 §1, ADR-0024).
    ///
    /// Until 0.4.0 this answered `describes = false` and there was nothing else
    /// it could do: the interface exported a single `run(name, attempt,
    /// inputs)`, the component dispatched by name inside itself, and from out
    /// here there was no list of names to publish and no signature to read. The
    /// WIT embedded in the `.wasm` did not help either — it said *"there is a
    /// `run` that takes a name and a list"*, which is true and useless. That
    /// was the bill for dispatching by name (ADR-0003); `describe` is the bill
    /// being paid.
    ///
    /// **An empty list is read as `describes = false`.** In gRPC the boolean
    /// tells apart "I serve nothing" from "do not check me" because an
    /// executor can legitimately serve zero steps; a component that serves
    /// zero steps has nothing to do, so the safe reading is the only useful
    /// one (ADR-0021 §4).
    ///
    /// A component that traps while describing itself is **not** a run-stopping
    /// error here: it comes back as `describes = false`, its steps come out as
    /// unchecked, and the sequence goes on — the same treatment as an executor
    /// that does not answer at all (`crates/motor/src/catalogo.rs`).
    #[allow(clippy::result_large_err)]
    async fn describe(&self, _r: Request<CatalogRequest>) -> Result<Response<Catalog>, Status> {
        // `block_in_place` for the same reason as in `invoke`, above.
        let steps = tokio::task::block_in_place(|| {
            Ok::<_, Status>(
                self.modules
                    .lock()
                    .map_err(|_| Status::internal("executor in use"))?
                    .catalog(),
            )
        })?;
        Ok(Response::new(Catalog {
            describes: !steps.is_empty(),
            steps,
            contract: CONTRACT,
            // Empty on purpose: with no objects there is no life to declare
            // (ADR-0022 §6). A component cannot hold one — the bridge rejects
            // a reference before it gets here.
            lifetime: String::new(),
        }))
    }
}

/// The directory this binary lives in — where its modules are, unless it was
/// told otherwise (ADR-0027).
///
/// Resolved from the executable itself and not from the working directory: the
/// bridge is spawned by `anvil`, which has its own cwd, and a department has to
/// mean the same thing wherever it is launched from.
fn own_directory() -> Result<PathBuf, String> {
    let exe = std::env::current_exe()
        .map_err(|e| format!("could not locate this executor's own binary: {e}"))?;
    exe.parent()
        .map(|d| d.to_path_buf())
        .ok_or_else(|| "this executor's binary has no directory".to_string())
}

/// What the bridge was told to serve.
struct Args {
    wasm: Option<PathBuf>,
    modules: Vec<PathBuf>,
    port: u16,
    bind: IpAddr,
    /// `--list`: print the catalog and exit, without listening. The
    /// *enumerate* operation of ADR-0025 §4 — what an editor needs, and what
    /// answers "which steps does this executor serve?" without starting a
    /// bench. The same door the Python executor already has.
    list: bool,
}

fn parse_args() -> Result<Args, String> {
    let mut wasm: Option<PathBuf> = None;
    let mut modules: Vec<PathBuf> = Vec::new();
    let mut port: u16 = 0;
    let mut bind: IpAddr = "127.0.0.1".parse().unwrap();
    let mut list = false;
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--wasm" => {
                i += 1;
                wasm = Some(PathBuf::from(args.get(i).ok_or("--wasm with no value")?));
            }
            "--modules" => {
                i += 1;
                modules.push(PathBuf::from(args.get(i).ok_or("--modules with no value")?));
            }
            "--list" => list = true,
            "--port" => {
                i += 1;
                port = args
                    .get(i)
                    .ok_or("--port with no value")?
                    .parse()
                    .map_err(|_| "--port is not a number")?;
            }
            "--bind" => {
                i += 1;
                bind = args
                    .get(i)
                    .ok_or("--bind with no value")?
                    .parse()
                    .map_err(|_| "--bind is not a valid IP")?;
            }
            other => return Err(format!("unknown flag: '{other}'")),
        }
        i += 1;
    }
    if wasm.is_some() && !modules.is_empty() {
        return Err(
            "--wasm and --modules are exclusive: one file, or one or more directories".to_string(),
        );
    }
    // Nothing said: **the executor finds its own modules**, next to its own
    // binary (ADR-0027). That is what makes a department a copyable folder —
    // the bridge and its `.wasm` together — and what keeps the path to them
    // out of anybody's sequence. Anvil is told where the executor is; where
    // its modules are is the executor's business.
    if wasm.is_none() && modules.is_empty() {
        modules.push(own_directory()?);
    }
    Ok(Args {
        wasm,
        modules,
        port,
        bind,
        list,
    })
}

/// `--list`: every module, its hash and the steps it serves with their
/// signature. Loads each module, because describing is the only way to know —
/// which is why this is a tooling operation and not something a run does
/// (ADR-0025 §4).
// `clippy::result_large_err`: as in `ModuleSet::catalog`, above.
#[allow(clippy::result_large_err)]
fn print_catalog(set: &mut ModuleSet) {
    let names: Vec<String> = set.modules.keys().cloned().collect();
    for module in names {
        let hash = set.modules[&module].hash.clone();
        let path = set.modules[&module].path.display().to_string();
        println!("{module}  sha256:{hash}");
        println!("    {path}");
        let specs = match set.component(&module).map(|c| c.describe()) {
            Ok(Ok(specs)) => specs,
            Ok(Err(status)) => {
                println!("    (does not describe itself: {})", status.message());
                continue;
            }
            Err(e) => {
                println!("    (could not be loaded: {e})");
                continue;
            }
        };
        if specs.is_empty() {
            println!("    (serves no steps)");
            continue;
        }
        for s in specs {
            let signature = s
                .inputs
                .iter()
                .map(|p| {
                    let t = match pb::ValueType::try_from(p.r#type) {
                        Ok(pb::ValueType::Number) => "number",
                        Ok(pb::ValueType::Text) => "text",
                        Ok(pb::ValueType::Boolean) => "boolean",
                        Ok(pb::ValueType::Reference) => "reference",
                        _ => "unspecified",
                    };
                    if p.required {
                        format!("{}: {t}", p.name)
                    } else {
                        format!("{}: {t} = optional", p.name)
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            // Printed exactly as a sequence must write it: qualified only when
            // this executor serves several modules. A listing that showed a
            // prefix the YAML must not carry would be a listing that lies.
            if set.qualified {
                println!("    {module}{MODULE_SEP}{}({signature})", s.name);
            } else {
                println!("    {}({signature})", s.name);
            }
            if !s.doc.is_empty() {
                println!("        {}", s.doc);
            }
            if !s.outputs.is_empty() {
                let outs = s
                    .outputs
                    .iter()
                    .map(|o| o.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                println!("        outputs: {outs}");
            }
        }
    }
}

fn main() {
    let args = match parse_args() {
        Ok(x) => x,
        Err(e) => {
            eprintln!(
                "usage: anvil-exec-wasm (--wasm <path.wasm> | --modules <dir>...) \
                 [--port <port>] [--bind <ip>] [--list]\n{e}"
            );
            std::process::exit(2);
        }
    };

    let engine = Engine::default();

    // The modules are read (name and hash) but **not compiled** here: loading
    // is per module and on demand, so a folder holding one broken `.wasm` still
    // serves the rest, and `--validate` with no catalog compiles nothing.
    let set = match &args.wasm {
        Some(path) => ModuleSet::from_file(engine, path),
        None => ModuleSet::from_dirs(engine, &args.modules),
    };
    let mut set = match set {
        Ok(s) => s,
        Err(e) => {
            eprintln!("anvil-exec-wasm: {e}");
            std::process::exit(1);
        }
    };

    if args.list {
        print_catalog(&mut set);
        return;
    }

    // The hash goes into the log on every start: with the module named
    // logically, this is what says which artifact actually answered
    // (ADR-0025 §6). It is **not** yet in the run's report — that needs a field
    // in the contract, and its own ADR.
    for (name, m) in &set.modules {
        eprintln!(
            "anvil-exec-wasm: module '{name}' ({}) sha256:{}",
            m.path.display(),
            m.hash
        );
    }

    let addr = SocketAddr::new(args.bind, args.port);
    let service = ExecutorService {
        modules: Arc::new(Mutex::new(set)),
    };

    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("could not create the runtime: {e}");
            std::process::exit(1);
        }
    };

    let server = Server::builder()
        .add_service(StepExecutorServer::new(service))
        .serve(addr);

    eprintln!("anvil-exec-wasm: listening on {addr}");

    // Clean exit: the host spawns the bridge with stdin piped; when the host
    // dies (or drops the `Child`), the pipe closes → EOF → the bridge exits.
    // Without this, a dead host would leave the bridge orphaned.
    let current_stdin = std::io::stdin();
    let _ = thread::spawn(move || {
        let mut buf = [0u8; 1];
        while let Ok(n) = std::io::Read::read(&mut current_stdin.lock(), &mut buf) {
            if n == 0 {
                std::process::exit(0);
            }
        }
    });

    // The server does not finish on its own (a loop serving requests). The
    // host kills the process when the sequence ends; by hand, Ctrl-C.
    let _ = rt.block_on(server);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A core module's header: `\0asm` + version 1.
    const CORE_MODULE_HEADER: [u8; 8] = [0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00];
    /// A component's header: `\0asm` + version 13, layer 1.
    const COMPONENT_HEADER: [u8; 8] = [0x00, 0x61, 0x73, 0x6d, 0x0d, 0x00, 0x01, 0x00];

    #[test]
    fn a_core_module_is_diagnosed_as_such() {
        let diag = diagnose_not_a_component(&CORE_MODULE_HEADER).expect("must diagnose");
        assert!(diag.contains("core module"), "{diag}");
        // The message has to name the RIGHT tool: since the SDK (ADR-0024) a
        // step is built with the plain toolchain, and sending someone to
        // install `cargo component` would send whoever is already lost down
        // the wrong road.
        assert!(
            diag.contains("cargo build --target wasm32-wasip2"),
            "{diag}"
        );
    }

    #[test]
    fn a_component_does_not_trigger_the_diagnosis() {
        assert_eq!(diagnose_not_a_component(&COMPONENT_HEADER), None);
    }

    /// Issue #24: a component whose `run` takes `attempt: u32` instead of the
    /// WIT's `s32` — the exact mistake BUG-06 made during the beta — used to
    /// fail with wasmtime's bare "failed to convert function to given type"
    /// and nothing else. `tests/fixtures/firma_no_casa.wasm` is a real
    /// component built against a hand-edited copy of `wit/anvil-step.wit`
    /// with that one line changed (everything else, `describe` included,
    /// matches); regenerating it needs a `wit-bindgen`-based crate exporting
    /// `anvil:step` with that edit, built for `wasm32-wasip2`.
    ///
    /// Seen to fail: reverting `LoadedComponent::load`'s call to
    /// `diagnose_signature_mismatch` (or the function itself) leaves the
    /// error at wasmtime's original wording, and this test goes red because
    /// neither "expected" nor "u32" appear in it.
    #[test]
    fn a_signature_mismatch_names_both_sides() {
        let bytes = std::fs::read(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("tests/fixtures/firma_no_casa.wasm"),
        )
        .expect("read fixture");
        let engine = Engine::default();
        let err = match LoadedComponent::load(&engine, &bytes) {
            Ok(_) => panic!("the mismatched component must not load"),
            Err(e) => e,
        };
        assert!(err.contains("could not instantiate"), "{err}");
        assert!(err.contains(EXPECTED_RUN), "{err}");
        assert!(err.contains("attempt: u32"), "{err}");
    }

    /// A component broken **beyond** the header is not this diagnosis's
    /// business: there wasmtime's message is the good one.
    #[test]
    fn a_component_with_a_junk_body_is_left_to_wasmtime() {
        let mut bytes = COMPONENT_HEADER.to_vec();
        bytes.extend_from_slice(&[0xff; 16]);
        assert_eq!(diagnose_not_a_component(&bytes), None);
    }

    #[test]
    fn a_file_that_is_not_wasm_is_diagnosed() {
        let diag = diagnose_not_a_component(b"name: i am not a wasm\n").expect("must diagnose");
        assert!(diag.contains("not a WebAssembly file"), "{diag}");
    }

    #[test]
    fn a_file_shorter_than_the_header_is_diagnosed() {
        let diag = diagnose_not_a_component(&COMPONENT_HEADER[..4]).expect("must diagnose");
        assert!(diag.contains("not a WebAssembly file"), "{diag}");
    }

    /// A `ModuleSet` with the given logical names and no file behind them.
    /// Enough to exercise name resolution, which is the part that decides
    /// **which module a step goes to** and never touches the disk.
    fn set_with(names: &[&str], qualified: bool) -> ModuleSet {
        let mut modules = BTreeMap::new();
        for n in names {
            modules.insert(
                (*n).to_string(),
                Module {
                    path: PathBuf::from(format!("{n}.wasm")),
                    hash: String::new(),
                    loaded: None,
                },
            );
        }
        ModuleSet {
            engine: Engine::default(),
            modules,
            qualified,
        }
    }

    /// Single-file mode keeps bare names: this is what every sequence written
    /// before ADR-0025 says, `ejemplos/demo_wasm.yaml` included.
    #[test]
    fn one_module_keeps_bare_step_names() {
        let set = set_with(&["hola_paso"], false);
        assert_eq!(
            set.resolve("medir_voltaje").unwrap(),
            ("hola_paso".to_string(), "medir_voltaje".to_string())
        );
    }

    #[test]
    fn a_qualified_name_picks_its_module() {
        let set = set_with(&["multimetro", "plc"], true);
        assert_eq!(
            set.resolve("plc/medir_voltaje").unwrap(),
            ("plc".to_string(), "medir_voltaje".to_string())
        );
        assert_eq!(
            set.resolve("multimetro/medir_voltaje").unwrap(),
            ("multimetro".to_string(), "medir_voltaje".to_string())
        );
    }

    /// The whole point of qualifying: the same step name in two modules is two
    /// different steps, and neither shadows the other.
    #[test]
    fn the_same_step_name_in_two_modules_does_not_collide() {
        let set = set_with(&["multimetro", "plc"], true);
        let (a, _) = set.resolve("multimetro/medir_voltaje").unwrap();
        let (b, _) = set.resolve("plc/medir_voltaje").unwrap();
        assert_ne!(a, b);
    }

    /// Serving several modules, a bare name is **not** guessed: which module a
    /// step lands on would then depend on what else is in the folder.
    ///
    /// Seen to fail by making `resolve` fall back to the only module that
    /// serves that step: the test goes green while the bridge starts choosing
    /// for the sequence.
    #[test]
    fn a_bare_name_is_rejected_when_several_modules_are_served() {
        let set = set_with(&["multimetro", "plc"], true);
        let err = set.resolve("medir_voltaje").unwrap_err();
        assert!(err.contains("has no module"), "{err}");
        // And it says what there is, so the fix does not need a second run.
        assert!(err.contains("multimetro") && err.contains("plc"), "{err}");
    }

    #[test]
    fn an_unknown_module_names_the_ones_served() {
        let set = set_with(&["multimetro"], true);
        let err = set.resolve("osciloscopio/medir").unwrap_err();
        assert!(err.contains("osciloscopio"), "{err}");
        assert!(err.contains("multimetro"), "{err}");
    }

    /// Two files with the same stem make a step name ambiguous, and serving the
    /// wrong one is worse than refusing to start: the run would measure with a
    /// module nobody asked for and the report would not say so.
    ///
    /// Seen to fail by dropping the collision check (`insert` overwrites, last
    /// one wins): the set builds happily with one module and the test stays
    /// green only because it asserts on the error.
    #[test]
    fn two_modules_with_the_same_logical_name_are_refused() {
        let dir = std::env::temp_dir().join(format!("anvil-modset-{}", std::process::id()));
        let a = dir.join("a");
        let b = dir.join("b");
        std::fs::create_dir_all(&a).expect("create dir a");
        std::fs::create_dir_all(&b).expect("create dir b");
        // The content does not matter: the clash is decided by the name, and
        // before anything is compiled.
        std::fs::write(a.join("multimetro.wasm"), COMPONENT_HEADER).expect("write a");
        std::fs::write(b.join("multimetro.wasm"), COMPONENT_HEADER).expect("write b");

        let err = ModuleSet::from_dirs(Engine::default(), &[a, b])
            .map(|_| ())
            .unwrap_err();
        assert!(
            err.contains("two modules are both called 'multimetro'"),
            "{err}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A directory with no `.wasm` is a misconfigured department, and saying so
    /// at start-up beats answering "I serve nothing" to every step.
    #[test]
    fn an_empty_module_directory_is_refused() {
        let dir = std::env::temp_dir().join(format!("anvil-modempty-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create dir");
        let err = ModuleSet::from_dirs(Engine::default(), std::slice::from_ref(&dir))
            .map(|_| ())
            .unwrap_err();
        assert!(err.contains("no '.wasm' module found"), "{err}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The logical name is the file stem: no extension, no path (ADR-0025 §3).
    #[test]
    fn the_logical_name_is_the_file_stem() {
        let dir = std::env::temp_dir().join(format!("anvil-modstem-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create dir");
        std::fs::write(dir.join("multimetro.wasm"), COMPONENT_HEADER).expect("write");
        let set =
            ModuleSet::from_dirs(Engine::default(), std::slice::from_ref(&dir)).expect("build");
        assert_eq!(set.module_names(), "multimetro");
        // And the hash is there without anything having been compiled.
        assert_eq!(set.modules["multimetro"].hash.len(), 64);
        assert!(set.modules["multimetro"].loaded.is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }
}

/// A WIT `Named` into the protobuf `Value` (the component's output).
fn named_to_proto(n: &Named) -> pb::Value {
    use exports::anvil::step::step::Value as ValueWit;
    let data = match &n.value {
        ValueWit::Number(x) => pb::value::Value::Number(*x),
        ValueWit::Text(s) => pb::value::Value::Text(s.clone()),
        ValueWit::Boolean(b) => pb::value::Value::Boolean(*b),
    };
    pb::Value {
        name: n.name.clone(),
        value: Some(data),
    }
}

/// The WIT's `value-type` into the protobuf `ValueType`.
///
/// The WIT has no `reference` (ADR-0022 §8), which is why the `match` is total
/// with no catch-all arm: if the WIT ever gains a type, this stops compiling,
/// which is exactly what is wanted.
fn type_to_proto(t: exports::anvil::step::step::ValueType) -> i32 {
    use exports::anvil::step::step::ValueType as TypeWit;
    let t = match t {
        TypeWit::Unspecified => pb::ValueType::Unspecified,
        TypeWit::Number => pb::ValueType::Number,
        TypeWit::Text => pb::ValueType::Text,
        TypeWit::Boolean => pb::ValueType::Boolean,
    };
    t as i32
}

/// A bare WIT `value` into the protobuf `Value`, with no name.
///
/// Only a parameter's `default` uses it, and that travels unnamed because the
/// name is already on the `ParameterSpec` holding it.
fn value_to_proto(v: &exports::anvil::step::step::Value) -> pb::Value {
    use exports::anvil::step::step::Value as ValueWit;
    let data = match v {
        ValueWit::Number(x) => pb::value::Value::Number(*x),
        ValueWit::Text(s) => pb::value::Value::Text(s.clone()),
        ValueWit::Boolean(b) => pb::value::Value::Boolean(*b),
    };
    pb::Value {
        name: String::new(),
        value: Some(data),
    }
}

/// A WIT `step-spec` into the protobuf `StepSpec`: the catalog, translated.
fn spec_to_proto(s: &exports::anvil::step::step::StepSpec) -> pb::StepSpec {
    pb::StepSpec {
        name: s.name.clone(),
        inputs: s
            .inputs
            .iter()
            .map(|p| pb::ParameterSpec {
                name: p.name.clone(),
                r#type: type_to_proto(p.type_),
                required: p.required,
                default: p.default.as_ref().map(value_to_proto),
                doc: p.doc.clone(),
            })
            .collect(),
        outputs: s
            .outputs
            .iter()
            .map(|o| pb::OutputSpec {
                name: o.name.clone(),
                r#type: type_to_proto(o.type_),
                doc: o.doc.clone(),
            })
            .collect(),
        doc: s.doc.clone(),
    }
}

/// Why a protobuf `Value` cannot be passed to the component.
#[derive(Debug, PartialEq)]
enum NotTranslatable {
    /// The `oneof` arrived empty: it does not say what type it is.
    Untyped(String),
    /// It is an object reference (ADR-0022).
    Reference(String),
}

/// A protobuf `Value` into the WIT's `Named` (the input parameter).
///
/// `Err` when there is no way to build the WIT `variant`, and the WIT has no
/// "unknown" arm on purpose: that is what makes it impossible to hand the
/// component a parameter nobody knows how to read. Two reasons:
///
/// - **The `oneof` arrived empty**: it does not say what type it is.
/// - **It is a reference** (contract 4, ADR-0022). This bridge's WIT is
///   `run(name, attempt, inputs) -> step-result`: a function, with no resources
///   and no state between calls (ADR-0020 §4d), so the user's component **has
///   nowhere to keep the object**. Handing it a reference would be handing it
///   an identifier it cannot resolve.
///
///   The failure is explicit and never a silence, which is exactly what
///   ADR-0022 §8 demands while the WIT stays untouched: giving the WASM state
///   is a decision with its own ADR, and until then this is said out loud.
fn proto_to_named(v: &pb::Value) -> Result<Named, NotTranslatable> {
    use exports::anvil::step::step::Value as ValueWit;
    let value = match v
        .value
        .as_ref()
        .ok_or_else(|| NotTranslatable::Untyped(v.name.clone()))?
    {
        pb::value::Value::Number(x) => ValueWit::Number(*x),
        pb::value::Value::Text(s) => ValueWit::Text(s.clone()),
        pb::value::Value::Boolean(b) => ValueWit::Boolean(*b),
        pb::value::Value::Reference(_) => return Err(NotTranslatable::Reference(v.name.clone())),
    };
    Ok(Named {
        name: v.name.clone(),
        value,
    })
}

#[cfg(test)]
mod contract_tests {
    use super::*;

    /// The net holding up the hand-copied `const CONTRACT`. See its comment:
    /// the bridge cannot link `modelo` into the binary, so the only way to keep
    /// the two copies together is to compare them in a test.
    #[test]
    fn the_bridge_contract_is_the_one_in_modelo() {
        assert_eq!(
            CONTRACT,
            modelo::proto::CONTRACT,
            "the bridge answers the echo on behalf of WASM components: if its \
             number falls behind, it claims to understand a contract it does not"
        );
    }

    #[test]
    fn an_untyped_parameter_does_not_reach_the_component() {
        // ADR-0019 Rule 2 at the bridge's border. If this started returning
        // `Ok`, a step would measure without a parameter it was sent.
        let v = pb::Value {
            name: "channel".into(),
            value: None,
        };
        assert_eq!(
            proto_to_named(&v).unwrap_err(),
            NotTranslatable::Untyped("channel".into())
        );
    }

    /// ADR-0022 §8: a reference reaching a WASM component is an **explicit**
    /// error, never a silence.
    ///
    /// This bridge's WIT is `run(name, attempt, inputs)`: a function, with no
    /// resources and no state between calls, so the component has nowhere to
    /// keep the object. Giving it state is a decision with its own ADR; until
    /// then this is said out loud, in the place that knows.
    ///
    /// Seen to fail by adding an arm turning it into `ValueWit::Text` with the
    /// payload: `proto_to_named` returns `Ok` and the component receives a
    /// string it cannot resolve.
    #[test]
    fn a_reference_does_not_reach_a_wasm_component() {
        let v = pb::Value {
            name: "rack".into(),
            value: Some(pb::value::Value::Reference(pb::Reference {
                executor: "bench".into(),
                lifetime: "v1".into(),
                payload: "s1".into(),
            })),
        };
        assert_eq!(
            proto_to_named(&v).unwrap_err(),
            NotTranslatable::Reference("rack".into())
        );
    }

    #[test]
    fn the_three_types_cross_the_border_both_ways() {
        use exports::anvil::step::step::Value as ValueWit;
        for wit in [
            ValueWit::Number(4.2),
            ValueWit::Text("bench-3".into()),
            ValueWit::Boolean(true),
        ] {
            let n = Named {
                name: "p".into(),
                value: wit,
            };
            let there = named_to_proto(&n);
            let back = proto_to_named(&there).expect("a typed value always comes back");
            assert_eq!(back.name, "p");
            assert_eq!(named_to_proto(&back), there);
        }
    }
}
