// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod anvil {
        pub mod paso {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod paso {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Un valor tipado que cruza la frontera del componente. Los tres tipos son
                /// los mismos del `oneof Valor` de `paso.proto` y de `expr::Value`: ni
                /// listas ni mapas (un parámetro que necesita estructura es un paso mal
                /// cortado, ADR-0020 §2).
                #[derive(Clone)]
                pub enum Valor {
                    Numero(f64),
                    Texto(_rt::String),
                    Booleano(bool),
                }
                impl ::core::fmt::Debug for Valor {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Valor::Numero(e) => {
                                f.debug_tuple("Valor::Numero").field(e).finish()
                            }
                            Valor::Texto(e) => {
                                f.debug_tuple("Valor::Texto").field(e).finish()
                            }
                            Valor::Booleano(e) => {
                                f.debug_tuple("Valor::Booleano").field(e).finish()
                            }
                        }
                    }
                }
                /// Un `valor` con su nombre. Con nombre y no posicional: el YAML se escribe
                /// y se revisa a mano, y reordenar dos parámetros no puede cambiar lo que
                /// mide el banco.
                #[derive(Clone)]
                pub struct Nombrado {
                    pub nombre: _rt::String,
                    pub valor: Valor,
                }
                impl ::core::fmt::Debug for Nombrado {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Nombrado")
                            .field("nombre", &self.nombre)
                            .field("valor", &self.valor)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct Resultado {
                    /// El veredicto del paso. Es texto porque así viaja en `paso.proto` y un
                    /// paso puede escribirse en cualquier lenguaje, pero el vocabulario es
                    /// **cerrado**: exactamente uno de estos cuatro literales, en minúscula.
                    ///
                    ///   "paso"     el paso cumplió su criterio
                    ///   "fallo"    la unidad no cumple — información sobre el DUT
                    ///   "error"    no se pudo juzgar — información sobre el banco o el paso
                    ///   "saltado"  no se ejecutó (lo pone el motor; un paso no lo devuelve)
                    ///
                    /// Cualquier otra cadena —"Paso", "PASS", "ok", y también "inconcluso",
                    /// que sólo produce el motor al agregar— convierte el paso en "error", con
                    /// un mensaje que nombra el valor recibido. Un estado que Anvil no entiende
                    /// no dice nada sobre la unidad (ADR-0019, Regla 2).
                    pub estado: _rt::String,
                    /// Texto libre para el informe: qué hizo el paso, o por qué no pudo.
                    pub mensaje: _rt::String,
                    /// La medida, si el paso mide. El **umbral no es del paso**: el motor
                    /// evalúa contra él el `limite` declarado en la secuencia (ADR-0008).
                    pub valor_medido: Option<f64>,
                    /// Valores con nombre que el paso devuelve **además** de la medida: una
                    /// temperatura de contexto, un número de serie leído, un coeficiente.
                    /// No participan en el veredicto; `asigna` los lee como
                    /// `resultado.salidas.<nombre>` (ADR-0020 §3).
                    ///
                    /// Sin `inout`: entra por `parametros`, sale por `salidas`, y no hay
                    /// tercer camino. Dárselo sería darle al paso una referencia al entorno
                    /// del motor, que es lo que ADR-0003 y ADR-0005 evitan.
                    pub salidas: _rt::Vec<Nombrado>,
                }
                impl ::core::fmt::Debug for Resultado {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Resultado")
                            .field("estado", &self.estado)
                            .field("mensaje", &self.mensaje)
                            .field("valor-medido", &self.valor_medido)
                            .field("salidas", &self.salidas)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base11 = arg3;
                    let len11 = arg4;
                    let mut result11 = _rt::Vec::with_capacity(len11);
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                        let e11 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            let l4 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let v10 = match l4 {
                                0 => {
                                    let e10 = {
                                        let l5 = *base
                                            .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<f64>();
                                        l5
                                    };
                                    Valor::Numero(e10)
                                }
                                1 => {
                                    let e10 = {
                                        let l6 = *base
                                            .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *base
                                            .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len8 = l7;
                                        let bytes8 = _rt::Vec::from_raw_parts(
                                            l6.cast(),
                                            len8,
                                            len8,
                                        );
                                        _rt::string_lift(bytes8)
                                    };
                                    Valor::Texto(e10)
                                }
                                n => {
                                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                                    let e10 = {
                                        let l9 = i32::from(
                                            *base
                                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        _rt::bool_lift(l9 as u8)
                                    };
                                    Valor::Booleano(e10)
                                }
                            };
                            Nombrado {
                                nombre: _rt::string_lift(bytes3),
                                valor: v10,
                            }
                        };
                        result11.push(e11);
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result12 = T::run(_rt::string_lift(bytes0), arg2, result11);
                    let ptr13 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Resultado {
                        estado: estado14,
                        mensaje: mensaje14,
                        valor_medido: valor_medido14,
                        salidas: salidas14,
                    } = result12;
                    let vec15 = (estado14.into_bytes()).into_boxed_slice();
                    let ptr15 = vec15.as_ptr().cast::<u8>();
                    let len15 = vec15.len();
                    ::core::mem::forget(vec15);
                    *ptr13.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
                    *ptr13.add(0).cast::<*mut u8>() = ptr15.cast_mut();
                    let vec16 = (mensaje14.into_bytes()).into_boxed_slice();
                    let ptr16 = vec16.as_ptr().cast::<u8>();
                    let len16 = vec16.len();
                    ::core::mem::forget(vec16);
                    *ptr13
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len16;
                    *ptr13
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr16.cast_mut();
                    match valor_medido14 {
                        Some(e) => {
                            *ptr13
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            *ptr13
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<f64>() = _rt::as_f64(e);
                        }
                        None => {
                            *ptr13
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    let vec20 = salidas14;
                    let len20 = vec20.len();
                    let layout20 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec20.len() * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result20 = if layout20.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout20).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout20);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec20.into_iter().enumerate() {
                        let base = result20
                            .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let Nombrado { nombre: nombre17, valor: valor17 } = e;
                            let vec18 = (nombre17.into_bytes()).into_boxed_slice();
                            let ptr18 = vec18.as_ptr().cast::<u8>();
                            let len18 = vec18.len();
                            ::core::mem::forget(vec18);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len18;
                            *base.add(0).cast::<*mut u8>() = ptr18.cast_mut();
                            match valor17 {
                                Valor::Numero(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>() = _rt::as_f64(e);
                                }
                                Valor::Texto(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec19 = (e.into_bytes()).into_boxed_slice();
                                    let ptr19 = vec19.as_ptr().cast::<u8>();
                                    let len19 = vec19.len();
                                    ::core::mem::forget(vec19);
                                    *base
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len19;
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr19.cast_mut();
                                }
                                Valor::Booleano(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (match e {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                            }
                        }
                    }
                    *ptr13
                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len20;
                    *ptr13
                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result20;
                    ptr13
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base11 = l4;
                    let len11 = l5;
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l6 = *base.add(0).cast::<*mut u8>();
                            let l7 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l8 {
                                0 => {}
                                1 => {
                                    let l9 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *base
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                                _ => {}
                            }
                        }
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                }
                pub trait Guest {
                    /// Los `parametros` llegan **ya evaluados**: el motor resuelve las
                    /// expresiones `${...}` del YAML contra su entorno antes de llamar
                    /// (ADR-0009). El paso no ve `locals` ni `file_globals`; se le pasa un valor.
                    fn run(
                        nombre: _rt::String,
                        intento: i32,
                        parametros: _rt::Vec<Nombrado>,
                    ) -> Resultado;
                }
                #[doc(hidden)]
                macro_rules! __export_anvil_paso_paso_0_2_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "anvil:paso/paso@0.2.0#run")] unsafe extern "C" fn
                        export_run(arg0 : * mut u8, arg1 : usize, arg2 : i32, arg3 : *
                        mut u8, arg4 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_run_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_anvil:paso/paso@0.2.0#run")] unsafe extern "C" fn
                        _post_return_run(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_run::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_anvil_paso_paso_0_2_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 6 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_anvil_paso_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::anvil::paso::paso::__export_anvil_paso_paso_0_2_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::anvil::paso::paso);
    };
}
#[doc(inline)]
pub(crate) use __export_anvil_paso_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:anvil:paso@0.2.0:anvil-paso:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 379] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfa\x01\x01A\x02\x01\
A\x02\x01B\x0a\x01q\x03\x06numero\x01u\0\x05texto\x01s\0\x08booleano\x01\x7f\0\x04\
\0\x05valor\x03\0\0\x01r\x02\x06nombres\x05valor\x01\x04\0\x08nombrado\x03\0\x02\
\x01ku\x01p\x03\x01r\x04\x06estados\x07mensajes\x0cvalor-medido\x04\x07salidas\x05\
\x04\0\x09resultado\x03\0\x06\x01@\x03\x06nombres\x07intentoz\x0aparametros\x05\0\
\x07\x04\0\x03run\x01\x08\x04\0\x15anvil:paso/paso@0.2.0\x05\0\x04\0\x1banvil:pa\
so/anvil-paso@0.2.0\x04\0\x0b\x10\x01\0\x0aanvil-paso\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
