#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 ANLACO
"""Anvil's Python step executor (ADR-0012) — a downloadable module.

A gRPC server speaking the `paso.proto` contract (`service StepExecutor`).
Anvil's engine sees it as one more endpoint: it dispatches name→endpoint and
does not know there is Python behind it.

**You do not edit this file to add a step.** Write a function, decorate it with
`@step` from `anvil_step`, and drop the module under the steps path; this
server discovers it, serves it, and describes it to Anvil (ADR-0021). That is
the whole point: the executor is a product you download, not a template you
fork — no recompiling the adapter, which is the TestStand pain ADR-0003 claims
to avoid.

Usage:
    python3 server.py                       # ./steps, listening on 127.0.0.1:9101
    python3 server.py --steps ~/my-steps    # your steps, wherever they live
    python3 server.py --port 9200           # another port
    python3 server.py --option simulator=192.168.1.50:4000   # LID: a legacy box
    python3 server.py --list                # print the catalog and exit

The steps path can be given as many times as needed, or through the
ANVIL_PYTHON_STEPS environment variable (a `os.pathsep`-separated list).
"""

import argparse
import os
import sys
from concurrent import futures

import grpc

import paso_pb2
import paso_pb2_grpc
from anvil_step import (
    BOOLEAN,
    NUMBER,
    OBJECTS,
    REFERENCE,
    REGISTRY,
    TEXT,
    Context,
    DiscoveryError,
    Reference,
    Result,
    discover,
)

HOST = "127.0.0.1"
PORT = 9101

#: Where steps are looked for when nothing says otherwise: a `steps/` folder in
#: the current directory. It is the "project path" of the issue's TestStand
#: analogy — you point the executor at your steps, it does not point at you.
STEPS_DEFAULT = "steps"

#: Environment variable holding the steps path, for when a service manager
#: starts the executor and there is no command line to edit.
STEPS_ENV = "ANVIL_PYTHON_STEPS"

# The contract version this executor speaks (ADR-0020 §4).
#
# It has to match `modelo::proto::CONTRACT` in the core. The engine checks this
# number — the "echo" — and turns the step into `error` if an executor that
# receives `inputs` answers with a lower one: an executor that ignores the
# inputs **measures something else and says pass**, and that false green is the
# only reason this number exists.
#
# Raise it in the core and forget it here, and this executor stops being able
# to run steps with parameters — which is the loud, correct failure.
#
# 4 is the object reference (ADR-0022): a fourth branch in `Value`'s `oneof`, a
# fourth `ValueType`, and the lifetime this executor publishes in its catalog.
CONTRACT = 4

#: Maps the SDK's four type names to the wire enum. A type the step did not
#: state stays `UNSPECIFIED` and Anvil leaves that parameter unchecked.
WIRE_TYPES = {
    NUMBER: paso_pb2.VALUE_TYPE_NUMBER,
    TEXT: paso_pb2.VALUE_TYPE_TEXT,
    BOOLEAN: paso_pb2.VALUE_TYPE_BOOLEAN,
    REFERENCE: paso_pb2.VALUE_TYPE_REFERENCE,
}


def value_to_python(v):
    """A wire `Value` to the Python type it stands for.

    Returns `None` if the `oneof` arrived with no branch: it does not say what
    type it is, and running the step without that parameter would be measuring
    something else in silence (ADR-0019, Rule 2). Careful: `None` here means
    "uninterpretable", not "absent" — an absent parameter is simply not in the
    list.
    """
    which = v.WhichOneof("value")
    if which is None:
        return None
    if which == "reference":
        # The three parts stay apart all the way to the step (ADR-0022 §4):
        # flattening them into one string here would make this executor the
        # place where a payload containing the separator goes wrong.
        return Reference(
            payload=v.reference.payload,
            lifetime=v.reference.lifetime,
            executor=v.reference.executor,
        )
    return getattr(v, which)


def inputs_of(request):
    """The request's inputs as a `dict`, or `(None, name)` if one is untyped."""
    out = {}
    for v in request.inputs:
        value = value_to_python(v)
        if value is None:
            return None, v.name
        out[v.name] = value
    return out, None


def fill_value(target, name, value):
    """Writes a Python value into a wire `Value`, `bool` first.

    In Python `True` is also an `int`; checking numbers first would describe a
    boolean default as the number 1.
    """
    target.name = name
    if isinstance(value, Reference):
        # `executor` is left as the step set it (normally empty): stamping it
        # is Anvil's half, and this process does not know what the sequence
        # called it (ADR-0022 §4). The lifetime is ours and we do say it.
        target.reference.payload = value.payload
        target.reference.lifetime = value.lifetime
        target.reference.executor = value.executor
    elif isinstance(value, bool):
        target.boolean = value
    elif isinstance(value, (int, float)):
        target.number = float(value)
    else:
        target.text = str(value)


def to_proto(name, result):
    """The wire answer for a step's `Result`, **always with the echo set**.

    The echo lives here, in the one place that builds the answer, so that there
    is no way to return a result without it: an executor that sometimes says it
    understands the contract and sometimes does not is worse than one that
    never did.
    """
    r = paso_pb2.StepResult(
        name=name,
        status=result.status,
        message=result.message,
        contract=CONTRACT,
    )
    if result.measured_value is not None:
        r.measured_value = str(result.measured_value)
    for n, v in result.outputs.items():
        fill_value(r.outputs.add(), n, v)
    return r


def to_proto_spec(spec):
    """One step's signature as the wire `StepSpec` (ADR-0021)."""
    out = paso_pb2.StepSpec(name=spec.name, doc=spec.doc)
    for p in spec.inputs:
        wire = out.inputs.add()
        wire.name = p.name
        wire.type = WIRE_TYPES.get(p.type, paso_pb2.VALUE_TYPE_UNSPECIFIED)
        wire.required = p.required
        wire.doc = p.doc
        # A default of `None` is not sent: the wire has no null, and sending an
        # empty `oneof` would be sending exactly what the receiver must reject.
        if p.default is not None:
            fill_value(wire.default, p.name, p.default)
    for o in spec.outputs:
        wire_out = out.outputs.add()
        wire_out.name = o.name
        wire_out.type = WIRE_TYPES.get(o.type, paso_pb2.VALUE_TYPE_UNSPECIFIED)
        wire_out.doc = o.doc
    return out


class StepExecutorServicer(paso_pb2_grpc.StepExecutorServicer):
    """The contract, served off the registry.

    There is no dispatch table here and no `if` on step names: the two RPCs
    read the same registry, so a step that runs is a step that is described,
    and neither can drift from the other.
    """

    def __init__(self, registry, options, objects=OBJECTS):
        self.registry = registry
        self.options = options
        self.objects = objects

    def Invoke(self, request, context):
        name = request.name
        inputs, untyped = inputs_of(request)
        if untyped is not None:
            return to_proto(
                name,
                Result.error(
                    f"the parameter '{untyped}' arrived untyped (none of the "
                    f"number/text/boolean branches): the step cannot know what "
                    f"to measure with"
                ),
            )

        s = self.registry.get(name)
        if s is None:
            # An unknown name is `error`, never an exception (RF-12). The list
            # is in the message because the mistake is nearly always a typo,
            # and the answer is right there.
            known = ", ".join(x.name for x in self.registry.catalog()) or "none"
            return to_proto(
                name,
                Result.error(
                    f"the python executor does not serve a step called "
                    f"'{name}' (it serves: {known})"
                ),
            )

        ctx = Context(
            attempt=request.attempt,
            options=self.options,
            step_name=name,
            objects=self.objects,
        )
        return to_proto(name, s.invoke(ctx, inputs))

    def Describe(self, request, context):
        """The catalog: every step served, with its signature (ADR-0021).

        `describes=True` is what separates "I serve no steps" from "do not
        check me". This executor always knows its own catalog, so it always
        says `True` — even when the catalog is empty, which is a real answer
        and one worth seeing.
        """
        # `lifetime` is what lets Anvil find out that this process died and was
        # born again while it held references to it — a fact about the world,
        # not about the sequence, so no type system answers it (ADR-0022 §6).
        catalog = paso_pb2.Catalog(
            describes=True, contract=CONTRACT, lifetime=self.objects.lifetime
        )
        for spec in self.registry.catalog():
            catalog.steps.append(to_proto_spec(spec))
        return catalog


def steps_paths(args):
    """The steps paths, in order of precedence: `--steps`, env var, default.

    The default is only used when it exists: an executor started with no steps
    to serve is a legitimate thing (it answers an empty catalog, and Anvil says
    so), while a typo'd `--steps` is not — `discover` rejects that one.
    """
    if args.steps:
        return args.steps
    del_entorno = os.environ.get(STEPS_ENV)
    if del_entorno:
        return [p for p in del_entorno.split(os.pathsep) if p]
    return [STEPS_DEFAULT] if os.path.isdir(STEPS_DEFAULT) else []


def parse_options(raw):
    """`--option key=value` pairs into a dict, rejecting what is not a pair."""
    options = {}
    for item in raw or []:
        key, sep, value = item.partition("=")
        if not sep or not key:
            raise SystemExit(f"--option takes key=value, not '{item}'")
        options[key] = value
    return options


def print_catalog(registry):
    """The catalog as text — the same information Anvil gets from `Describe`.

    It exists so that "which steps does this executor serve?" can be answered
    without starting a bench or reading this file.
    """
    if not len(registry):
        print("this executor serves no steps (nothing found under the steps path)")
        return
    for spec in registry.catalog():
        firma = ", ".join(
            f"{p.name}: {p.type}" + ("" if p.required else f" = {p.default!r}")
            for p in spec.inputs
        )
        print(f"{spec.name}({firma})")
        if spec.doc:
            print(f"    {spec.doc}")
        if spec.outputs:
            print(f"    outputs: {', '.join(f'{o.name}: {o.type}' for o in spec.outputs)}")


def main():
    parser = argparse.ArgumentParser(description="Anvil's Python step executor (ADR-0012)")
    parser.add_argument("--port", type=int, default=PORT)
    parser.add_argument(
        "--steps",
        action="append",
        metavar="PATH",
        help=f"directory or .py file holding your steps (default: ./{STEPS_DEFAULT}, "
        f"or ${STEPS_ENV}). Repeatable",
    )
    parser.add_argument(
        "--option",
        action="append",
        metavar="KEY=VALUE",
        help="deployment configuration handed to the steps as ctx.options "
        "(e.g. simulator=192.168.1.50:4000)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the catalog of served steps and exit",
    )
    args = parser.parse_args()
    options = parse_options(args.option)

    rutas = steps_paths(args)
    try:
        cargados = discover(rutas)
    except DiscoveryError as e:
        # Loud and up front: an executor that serves the wrong catalog is worse
        # than one that refuses to start.
        print(f"could not load the steps: {e}", file=sys.stderr)
        raise SystemExit(1)

    if args.list:
        print_catalog(REGISTRY)
        return

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    paso_pb2_grpc.add_StepExecutorServicer_to_server(
        StepExecutorServicer(REGISTRY, options), server
    )
    server.add_insecure_port(f"{HOST}:{args.port}")
    server.start()
    print(
        f"python executor listening on {HOST}:{args.port} — "
        f"{len(REGISTRY)} step(s) from {len(cargados)} module(s): "
        f"{', '.join(s.name for s in REGISTRY.catalog()) or 'none'}"
    )
    if not len(REGISTRY):
        print(
            f"warning: no steps found. Put them under ./{STEPS_DEFAULT}, pass "
            f"--steps PATH, or set ${STEPS_ENV}",
            file=sys.stderr,
        )
    sys.stdout.flush()
    server.wait_for_termination()


if __name__ == "__main__":
    main()
